### PR TITLE
Fix Typo of south korea name in 2nd table (incarcerated number)

### PR DESCRIPTION
**Pull request by SMSadegh19**
It seems you mean "Republic of South Korea".
But you wrote "Republic of ".

### CODE REVIEW

**Comment by SMSadegh19** [comment]
@MKorostoff
Hi!
Your project is very excellent and I love it.
I sent this PR with love.

**Comment by mkorostoff** [comment]
@SMSadegh19 I'm pretty impressed that you managed to figure out what country I was talking about, even I didn't remember.

**Comment by mkorostoff** [comment]
@SMSadegh19 could you actually make it say just "South Korea" instead of "Republic of South Korea"? long text sometimes overflows

**Comment by SMSadegh19** [comment]
@MKorostoff
Sure! I changed "Republic of South Korea" into "South Korea".
I noticed this in the translation process.

**Pull request merged**
